### ISSUE TITLE
Move main dependencies and base styles

### ISSUE THREAD

**Issue by ryanlabouve** [locks/ember-styleguide#4]
At first glance here's what I'm considering taking:
* [x] ember cli sass
* [x] bourbon
* [x] neat
* [x] normalize-scss
* [ ] code highlighting (via coderay?)
* [x] fonts
* [x] fontello (i.e. icons)
* [x] /source/stylesheets/base/*
* [x] /source/stylesheets/mixins/*

I'll likely open a WIP PR on `guides` just to show the diff of what's moving and open a PR on the docs viewer.

Outstanding Questions
* ~~Initially are we using bower to grab the dependencies? (e.g. bourbon & neat)~~

**Comment by locks** [comment]
Hm, since this is an Ember addon, maybe use the addons and save yourself some work. You can see how I'm using them at https://github.com/locks/guias.

**Comment by ryanlabouve** [comment]
https://github.com/locks/ember-styleguide/pull/5

**Comment by ryanlabouve** [comment]
I've migrated most style things. I need to check on code highlighting and potentially pare down style that is not generic enough to be in styleguide (but IMO this isn't an issue)? 

Screenshot of header component I made for testing running in the dummy app:
![dummy](https://cloud.githubusercontent.com/assets/1318878/14291426/2fb4d292-fb29-11e5-98ab-ea415406dbd9.jpg)

**Comment by ryanlabouve** [comment]
@locks Any objection merging and moving code highlighting to issue?

**Comment by locks** [comment]
>  I need to check on code highlighting and potentially pare down style that is not generic enough to be in styleguide (but IMO this isn't an issue)?

:ok_hand: 

> @locks Any objection merging and moving code highlighting to issue?

:ok_hand:

**Comment by locks** [comment]
Merged the PR.
